# Generated by Django 4.2.29 on 2026-03-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.AutoField(db_column='id_question', primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('bloom_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], db_column='bloom_level', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('id_subject', models.ForeignKey(db_column='id_subject', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
                'ordering': ['id_subject', 'id_question'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id_answer', models.AutoField(db_column='id_answer', primary_key=True, serialize=False)),
                ('answer_text', models.TextField(db_column='answer_text')),
                ('is_correct', models.BooleanField(db_column='is_correct')),
                ('id_question', models.ForeignKey(db_column='id_question', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answer',
                'ordering': ['id_question', 'id_answer'],
            },
        ),
    ]
