# Generated by Django 5.0 on 2026-04-06 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_audit_fields_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('question', models.OneToOneField(db_column='id_question', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='code_question', serialize=False, to='questions.question')),
                ('language', models.CharField(db_column='language', default='python', max_length=32)),
                ('test_cases', models.JSONField(db_column='test_cases', default=list)),
            ],
            options={
                'verbose_name': 'Code question',
                'verbose_name_plural': 'Code questions',
                'db_table': 'code_question',
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id_question'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], db_column='difficulty', default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, db_column='image_url', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(db_column='points', default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple choice'), ('MULTIPLE_SELECTION', 'Multiple selection'), ('OPEN', 'Open'), ('CODE', 'Code')], db_column='question_type', default='MULTIPLE_CHOICE', max_length=32),
        ),
    ]
