# Generated by Django 5.0 on 2026-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_text',
            field=models.TextField(blank=True, db_column='answer_text', default=''),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='code_answer',
            field=models.TextField(blank=True, db_column='code_answer', default=''),
        ),
    ]
