# Generated by Django 5.0 on 2026-03-14 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(db_column='id_person', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('id_group', models.ForeignKey(blank=True, db_column='id_group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='academic.group')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'person',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Administrator')], max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('id_person', models.OneToOneField(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='users.person')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'user_account',
                'ordering': ['username'],
            },
        ),
    ]
