# Generated by Django 4.2.29 on 2026-03-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, db_table='teacher_subject', related_name='teachers', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='matricula',
            field=models.CharField(blank=True, db_column='matricula', help_text='Matrícula institucional única del usuario.', max_length=20, null=True, unique=True),
        ),
    ]
