# Generated by Django 5.0 on 2026-03-16 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id_term', models.AutoField(db_column='id_term', primary_key=True, serialize=False)),
                ('term_name', models.CharField(db_column='term_name', max_length=100)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'db_table': 'term',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(db_column='id_subject', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('id_term', models.ForeignKey(db_column='id_term', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.term')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(db_column='id_group', primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_column='group_name', max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('id_term', models.ForeignKey(db_column='id_term', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academic.term')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'group',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id_unit', models.AutoField(db_column='id_unit', primary_key=True, serialize=False)),
                ('unit_name', models.CharField(db_column='unit_name', max_length=150)),
                ('unit_number', models.IntegerField(db_column='unit_number')),
                ('id_subject', models.ForeignKey(db_column='id_subject', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'unit',
                'ordering': ['id_subject', 'unit_number'],
            },
        ),
    ]
