# Generated by Django 5.0 on 2026-03-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id_generation', models.AutoField(db_column='id_generation', primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
                ('total_levels', models.PositiveIntegerField(db_column='total_levels', default=11)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Generation',
                'verbose_name_plural': 'Generations',
                'db_table': 'generation',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(db_column='id_subject', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('level_number', models.PositiveIntegerField(db_column='level_number')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
                'ordering': ['level_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id_period', models.AutoField(db_column='id_period', primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('period_name', models.CharField(choices=[('Enero-Abril', 'Enero-Abril'), ('Mayo-Agosto', 'Mayo-Agosto'), ('Septiembre-Diciembre', 'Septiembre-Diciembre')], db_column='period_name', max_length=50)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(db_column='end_date')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'period',
                'ordering': ['-year', 'period_name'],
                'unique_together': {('year', 'period_name')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id_unit', models.AutoField(db_column='id_unit', primary_key=True, serialize=False)),
                ('unit_name', models.CharField(db_column='unit_name', max_length=150)),
                ('unit_number', models.IntegerField(db_column='unit_number')),
                ('id_subject', models.ForeignKey(db_column='id_subject', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academic.subject')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(db_column='id_group', primary_key=True, serialize=False)),
                ('group_letter', models.CharField(db_column='group_letter', max_length=5)),
                ('academic_level', models.PositiveIntegerField(db_column='academic_level')),
                ('status', models.BooleanField(default=True)),
                ('id_generation', models.ForeignKey(db_column='id_generation', on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='academic.generation')),
                ('id_period', models.ForeignKey(blank=True, db_column='id_period', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='academic.period')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'group',
                'ordering': ['id_generation', 'group_letter'],
                'unique_together': {('id_generation', 'group_letter')},
            },
        ),
    ]
