# Generated by Django 5.0 on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        # ===== Generation =====
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id_generation', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
                ('total_levels', models.PositiveIntegerField(default=11)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'generation',
                'ordering': ['-year'],
            },
        ),

        # ===== Period =====
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id_period', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('period_name', models.CharField(
                    max_length=50,
                    choices=[
                        ('Enero-Abril', 'Enero-Abril'),
                        ('Mayo-Agosto', 'Mayo-Agosto'),
                        ('Septiembre-Diciembre', 'Septiembre-Diciembre')
                    ]
                )),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'period',
                'ordering': ['-year', 'period_name'],
                'unique_together': {('year', 'period_name')},
            },
        ),

        # ===== Subject =====
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('level_number', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subject',
                'ordering': ['level_number', 'name'],
            },
        ),

        # ===== Unit =====
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id_unit', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=150)),
                ('unit_number', models.IntegerField()),
                ('id_subject', models.ForeignKey(
                    to='academic.subject',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='units'
                )),
            ],
            options={
                'db_table': 'unit',
            },
        ),

        # ===== Group =====
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('group_letter', models.CharField(max_length=5)),
                ('academic_level', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('id_generation', models.ForeignKey(
                    to='academic.generation',
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='groups'
                )),
                ('id_period', models.ForeignKey(
                    to='academic.period',
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='groups',
                    null=True,
                    blank=True
                )),
            ],
            options={
                'db_table': 'group',
                'ordering': ['id_generation', 'group_letter'],
                'unique_together': {('id_generation', 'group_letter')},
            },
        ),
    ]