# Generated by Django 5.0 on 2026-04-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_group_id_period'),
        ('users', '0002_alter_user_matricula_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, db_column='teacher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_groups', to='users.teacherprofile'),
        ),
    ]
