# Generated by Django 5.0 on 2026-04-09 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_add_teacher_to_group'),
        ('users', '0002_alter_user_matricula_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.CreateModel(
            name='GroupTeacherAssignment',
            fields=[
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_assignment', models.AutoField(db_column='id_assignment', primary_key=True, serialize=False)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academic.group')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by_set', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='academic.subject')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='users.teacherprofile')),
            ],
            options={
                'verbose_name': 'Group Teacher Assignment',
                'verbose_name_plural': 'Group Teacher Assignments',
                'db_table': 'group_teacher_assignment',
                'unique_together': {('group', 'subject')},
            },
        ),
    ]
