# Generated by Django 5.0 on 2026-04-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_remove_period_dates'),
        ('academic', '0007_replace_teacher_fk_with_assignment_table'),
    ]

    operations = [
    ]
