# Generated by Django 5.0 on 2026-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_merge_20260410_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['period_name'], 'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_name',
            field=models.CharField(choices=[('Enero-Abril', 'Enero-Abril'), ('Mayo-Agosto', 'Mayo-Agosto'), ('Septiembre-Diciembre', 'Septiembre-Diciembre')], db_column='period_name', max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='period',
            name='year',
        ),
    ]
