# Generated by Django 5.0 on 2026-04-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_remove_period_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_letter',
            field=models.CharField(db_column='group_letter', max_length=1),
        ),
    ]
