# Generated by Django 5.0 on 2026-04-14 15:43

from django.db import migrations, models


def truncate_group_letter(apps, schema_editor):
    """Truncate existing group_letter values to 1 character before applying constraint."""
    Group = apps.get_model('academic', 'Group')
    for group in Group.objects.filter(group_letter__isnull=False):
        if len(group.group_letter) > 1:
            group.group_letter = group.group_letter[0]
            group.save(update_fields=['group_letter'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_remove_period_year'),
    ]

    operations = [
        migrations.RunPython(truncate_group_letter, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='group',
            name='group_letter',
            field=models.CharField(db_column='group_letter', max_length=1),
        ),
    ]
