# Generated by Django 5.0 on 2026-04-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_restrict_group_letter_one_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='end_year',
            field=models.IntegerField(blank=True, db_column='end_year', null=True),
        ),
    ]
