# Generated by Django 5.0 on 2026-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField()),
                ('operation_type', models.TextField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('db_user', models.TextField(blank=True, null=True)),
                ('app_user', models.TextField(blank=True, null=True)),
                ('client_addr', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-changed_at'],
                'managed': False,
            },
        ),
    ]
