# Generated by Django 5.0 on 2026-03-16 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('questions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id_exam', models.AutoField(db_column='id_exam', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('secure_mode', models.BooleanField(db_column='secure_mode', default=False)),
                ('creation_date', models.DateField(db_column='creation_date')),
                ('status', models.BooleanField(default=True)),
                ('id_subject', models.ForeignKey(db_column='id_subject', on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='academic.subject')),
                ('id_teacher', models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.RESTRICT, related_name='created_exams', to='users.person')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exam',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamPerson',
            fields=[
                ('id_exam_person', models.AutoField(db_column='id_exam_person', primary_key=True, serialize=False)),
                ('assignment_date', models.DateField(db_column='assignment_date')),
                ('start_datetime', models.DateTimeField(blank=True, db_column='start_datetime', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_column='end_datetime', null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('not_presented', 'Not Presented')], max_length=50)),
                ('id_exam', models.ForeignKey(db_column='id_exam', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam')),
                ('id_person', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to='users.person')),
            ],
            options={
                'verbose_name': 'Exam Person',
                'verbose_name_plural': 'Exam Persons',
                'db_table': 'exam_person',
                'ordering': ['-assignment_date'],
                'unique_together': {('id_exam', 'id_person')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id_exam_question', models.AutoField(db_column='id_exam_question', primary_key=True, serialize=False)),
                ('question_order', models.IntegerField(db_column='question_order')),
                ('id_exam', models.ForeignKey(db_column='id_exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam')),
                ('id_question', models.ForeignKey(db_column='id_question', on_delete=django.db.models.deletion.RESTRICT, related_name='question_exams', to='questions.question')),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'db_table': 'exam_question',
                'ordering': ['id_exam', 'question_order'],
                'unique_together': {('id_exam', 'id_question')},
            },
        ),
    ]
