# Generated by Django 5.0 on 2026-03-28 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='id_teacher',
            field=models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.RESTRICT, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examperson',
            name='id_exam',
            field=models.ForeignKey(db_column='id_exam', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examperson',
            name='id_person',
            field=models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='id_exam',
            field=models.ForeignKey(db_column='id_exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='id_question',
            field=models.ForeignKey(db_column='id_question', on_delete=django.db.models.deletion.RESTRICT, related_name='question_exams', to='questions.question'),
        ),
        migrations.AlterUniqueTogether(
            name='examperson',
            unique_together={('id_exam', 'id_person')},
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('id_exam', 'id_question')},
        ),
    ]
