# Generated by Django 4.2.29 on 2026-03-17 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examperson',
            name='id_person',
            field=models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='id_subject',
            field=models.ForeignKey(db_column='id_subject', on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='academic.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='id_teacher',
            field=models.ForeignKey(db_column='id_teacher', on_delete=django.db.models.deletion.RESTRICT, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='examquestion',
            unique_together={('id_exam', 'id_question')},
        ),
        migrations.AlterUniqueTogether(
            name='examperson',
            unique_together={('id_exam', 'id_person')},
        ),
    ]
