# Generated by Django 5.0 on 2026-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Medio'), ('hard', 'Difícil')], db_column='difficulty_level', default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='unit_number',
            field=models.PositiveIntegerField(db_column='unit_number', default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', null=True),
        ),
    ]
