# Generated by Django 5.0 on 2026-04-03 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('exams', '0003_exam_created_at_exam_difficulty_level_exam_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id_assignment', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado')], db_column='status', default='pending', max_length=20)),
                ('score', models.DecimalField(blank=True, db_column='score', decimal_places=2, max_digits=5, null=True)),
                ('is_passed', models.BooleanField(blank=True, db_column='is_passed', null=True)),
                ('assigned_at', models.DateTimeField(db_column='assigned_at')),
                ('available_from', models.DateTimeField(db_column='available_from')),
                ('available_to', models.DateTimeField(db_column='available_to')),
                ('attempt_date', models.DateTimeField(blank=True, db_column='attempt_date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='exams.exam')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.RESTRICT, related_name='exam_assignments', to='academic.group')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Assignment',
                'verbose_name_plural': 'Exam Assignments',
                'db_table': 'exam_assignment',
                'ordering': ['-assigned_at'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
