# Generated by Django 5.0 on 2026-04-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_add_exam_assignment_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamPerson',
        ),
    ]
