# Generated by Django 5.0 on 2026-04-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('exams', '0005_remove_exam_person_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGroupAssignment',
            fields=[
                ('id_exam_group', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('available_from', models.DateTimeField(db_column='available_from')),
                ('available_to', models.DateTimeField(db_column='available_to')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_column='assigned_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='exams.exam')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.RESTRICT, related_name='exam_group_assignments', to='academic.group')),
            ],
            options={
                'verbose_name': 'Exam Group Assignment',
                'verbose_name_plural': 'Exam Group Assignments',
                'db_table': 'exam_group_assignment',
                'ordering': ['group'],
                'unique_together': {('exam', 'group')},
            },
        ),
    ]
