# Generated by Django 5.0 on 2026-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_add_exam_group_assignment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='minimum_score',
            field=models.DecimalField(db_column='minimum_score', decimal_places=2, default=8.0, help_text='Calificación mínima para aprobar el examen.', max_digits=5),
        ),
    ]
