# Generated by Django 5.0 on 2026-04-05 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_add_minimum_score_to_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='examassignment',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='examgroupassignment',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='exam',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examgroupassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='examgroupassignment',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='secure_mode',
            field=models.BooleanField(db_column='secure_mode', default=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
