# Generated by Django 5.0 on 2026-04-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_rename_updated_at_exam_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
    ]
