# Generated by Django 5.0 on 2026-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_exam_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='modified_at',
            field=models.DateField(auto_now=True, db_column='updated_at', null=True),
        ),
        migrations.AlterField(
            model_name='examassignment',
            name='created_at',
            field=models.DateField(auto_now_add=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='examassignment',
            name='modified_at',
            field=models.DateField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='examgroupassignment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='examgroupassignment',
            name='modified_at',
            field=models.DateField(auto_now=True, db_column='updated_at'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='modified_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
