# Generated by Django 5.0 on 2026-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_audit_fields_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='creation_date',
            field=models.DateTimeField(db_column='creation_date'),
        ),
    ]
